app.py
from flask import Flask
from database.db import start_db 
from routes.routes import cliente_blueprint

app = Flask(__name__)

app.register_blueprint(cliente_blueprint)

if __name__ == '__main__':
    start_db()
    app.run(debug=True)

routes/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
import sqlite3
from config.config import DATABASE
from validation.validation import validation

cliente_blueprint = Blueprint('cliente', __name__)

@cliente_blueprint.route('/')
def index():
    """
    Exibe a lista de todos os clientes cadastrados.

    Returns:
        Renderização do template 'index.html' com os dados dos clientes,
        ou uma mensagem de erro.
    """
    try:
        with sqlite3.connect(DATABASE) as conn:
            cliente = conn.execute("SELECT * FROM cliente").fetchall() 
        return render_template('index.html', cliente = cliente) 
    except Exception as e:
        print(f"Erro as listar clientes: {e}")
        return f"Erro ao carregar clientes: {e}", 500

@cliente_blueprint.route('/criar', methods = ['GET', 'POST'])  
def criar():
    """
    Cria um novo cliente a partir dos dados enviados via formulário.

    Returns:
        - Em caso de sucesso: redireciona para a rota de listagem.
        - Em caso de erro: renderiza o formulário com mensagens de erro.
    """
    if request.method == 'POST': 
        nome = request.form['nome']
        cpf = request.form['cpf']
        email = request.form['email']

        erros = validation(nome, cpf, email)

        if erros:
            return render_template('criar.html', erros = erros, nome = nome, cpf = cpf, email = email)
        
        try:
            with sqlite3.connect(DATABASE) as conn:
                conn.execute(
                    "INSERT INTO cliente (nome, cpf, email) VALUES (?, ?, ?)",
                    (nome, cpf, email)
                )
            return redirect(url_for('cliente.index'))
        except Exception as e:
            print(f"Erro ao criar cliente: {e}")
            return f"Erro ao criar cliente: {e}", 500
    return render_template('criar.html')        

@cliente_blueprint.route('/editar/<int:cliente_id>', methods = ['GET', 'POST'])
def editar(cliente_id):
    """
    Edita os dados de um cliente existente.

    Args:
        cliente_id (int): ID do cliente a ser editado.

    Returns:
        - Em caso de sucesso: redireciona para a rota de listagem.
        - Em caso de erro: renderiza o formulário com mensagens de erro
          ou retorna erro 404/500 conforme o caso.
    """
    try:
        with sqlite3.connect(DATABASE) as conn:
            if request.method == 'POST':
                nome = request.form['nome']
                cpf = request.form['cpf']
                email = request.form['email']

                erros = validation(nome, cpf, email)

                if erros:
                    cliente = {'id': cliente_id, 'nome': nome, 'cpf': cpf, 'email': email}
                    return render_template('editar.html', cliente = cliente, erros = erros)
                
                conn.execute(
                    "UPDATE cliente SET nome = ?, cpf = ?, email = ? WHERE id = ?",
                    (nome, cpf, email, cliente_id)
                )
                return redirect(url_for('cliente.index'))
            
            cliente = conn.execute(
                "SELECT * FROM cliente WHERE id = ?",
                (cliente_id,)
            ).fetchone()

            if cliente is None:
                return "Cliente não encontrado.", 404
            
        return render_template('editar.html', cliente = cliente)  

    except Exception as e:
        print(f"Erro ao editar cliente: {e}")
        return f"Erro ao editar cliente: {e}", 500

@cliente_blueprint.route('/apagar/<int:cliente_id>') 
def apagar(cliente_id):
    """
    Exclui um cliente do banco de dados.

    Args:
        cliente_id (int): ID do cliente a ser removido.

    Returns:
        Redireciona para a página principal ou exibe mensagem de erro.
    """
    try:
        with sqlite3.connect(DATABASE) as conn:
            conn.execute("DELETE FROM cliente WHERE id = ?", (cliente_id,))
        return redirect(url_for('cliente.index'))
    except Exception as e:
        print(f"Erro ao apagar cliente: {e}")
        return f"Erro ao apagar cliente. {e}", 500

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="#">
        <link rel="stylesheet" href="{{ url_for('static', filename='/bootstrap/bootstrap.min.css') }}">
        <title>Crud Flask</title>
    </head>
    <body>
        <div class="container">
            <div>
                <h1 class="display-4">CRUD FLASK</h1>
            </div>
            {% block content %}{% endblock %}
        </div>    
    </body>
</html>

templates/criar.html
{% extends "base.html" %}

{% block content %}
    <h2 class="display-6 text-center">NOVO CLIENTE</h2>
    <a href="{{ url_for('cliente.index') }}"><input type="button" class="btn btn-secondary" value="Voltar"></a><br /><br />
    <form method="POST">
        <div class="form-group">
            <label for="nome">NOME</label>
            <input type="text" class="form-control" name="nome" aria-describedby="emailHelp" />
            {% if 'nome' in erros %} <span class="text-danger fw-bold">{{ erros.nome }}</span> {% endif %}
        </div>
        <div class="form-group">
            <label for="cpf">Cpf</label>
            <input type="text" class="form-control" name="cpf" />
            {% if 'cpf' in erros %} <span class="text-danger fw-bold">{{ erros.cpf }}</span> {% endif %}
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" name="email" />
            {% if 'email' in erros %} <span class="text-danger fw-bold">{{ erros.email }}</span> {% endif %}
        </div><br />
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
{% endblock %}

templates/editar.html
{% extends "base.html" %}

{% block content %}
    <h2 class="display-6 text-center">EDITAR CLIENTE</h2>
    <a href="{{ url_for('cliente.index') }}"><input type="button" class="btn btn-secondary" value="Voltar"></a><br /><br />
    <form method="POST">
        <div class="form-group">
            <label for="nome">NOME</label>
            <input type="text" class="form-control" name="nome" aria-describedby="emailHelp" placeholder="{{ cliente['nome'] }}" />
            {% if 'nome' in erros %} <span class="text-danger fw-bold">{{ erros.nome }}</span> {% endif %}
        </div>
        <div class="form-group">
            <label for="cpf">Cpf</label>
            <input type="text" class="form-control" name="cpf" placeholder="{{ cliente['cpf'] }}" />
            {% if 'cpf' in erros %} <span class="text-danger fw-bold">{{ erros.cpf }}</span> {% endif %}
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" name="email" placeholder="{{ cliente['email'] }}" />
            {% if 'email' in erros %} <span class="text-danger fw-bold">{{ erros.email }}</span> {% endif %}
        </div><br />
        <button type="submit" class="btn btn-primary">Atualizar</button>
    </form>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <h2 class="display-6 text-center">LISTA DE CLIENTES</h2>
    <a href="{{ url_for('cliente.criar') }}"><input type="button" class="btn btn-primary" value="Novo Cliente"></a><br /><br />
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col" class="text-center">Id</th>
                <th scope="col" class="text-center">Nome</th>
                <th scope="col" class="text-center">Cpf</th>
                <th scope="col" class="text-center">Email</th>
                <th scope="col" class="text-center">Editar</th>
                <th scope="col" class="text-center">Excluir</th>
            </tr>
        </thead>
        <tbody>
            {% for cliente in cliente %}
            <tr>
                <td class="text-center">{{ cliente[0] }}</td>
                <td class="text-center">{{ cliente[1] }}</td>
                <td class="text-center">{{ cliente[2] }}</td>
                <td class="text-center">{{ cliente[3] }}</td>
                <td class="text-center"><a href="{{ url_for('cliente.editar', cliente_id = cliente[0]) }}"><input type="button" class="btn btn-secondary" value="Editar"></a></td>
                <td class="text-center"><a href="{{ url_for('cliente.apagar', cliente_id = cliente[0]) }}"  onclick="return confirm('Confirmar exclusão?')"><input type="button" class="btn btn-danger" value="Excluir"></a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}